/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/torch/utils/cpp_extension.py:416: UserWarning: The detected CUDA version (12.1) has a minor version mismatch with the version that was used to compile PyTorch (12.4). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/torch/utils/cpp_extension.py:426: UserWarning: There are no g++ version bounds defined for CUDA version 12.1
  warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/torch/utils/cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Emitting ninja build file /work/tesi_pcarboni/cl_detr/models/ops/build/temp.linux-x86_64-cpython-312/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
Traceback (most recent call last):
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 2104, in _run_ninja_build
    subprocess.run(
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/tesi_pcarboni/cl_detr/models/ops/setup.py", line 54, in <module>
    setup(
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
    self.run_command(cmd)
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/setuptools/dist.py", line 945, in run_command
    super().run_command(command)
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/setuptools/dist.py", line 945, in run_command
    super().run_command(command)
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 93, in run
    _build_ext.run(self)
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 868, in build_extensions
    build_ext.build_extensions(self)
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
    self._build_extensions_serial()
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
    self.build_extension(ext)
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 254, in build_extension
    _build_ext.build_extension(self, ext)
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
    objects = self.compiler.compile(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 681, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 1784, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 2120, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: pol_carboni (pol_carboni-unimore). Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: pol_carboni (pol_carboni-unimore). Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: pol_carboni (pol_carboni-unimore). Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: pol_carboni (pol_carboni-unimore). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /homes/pcarboni/.netrc
wandb: Appending key for api.wandb.ai to your netrc file: /homes/pcarboni/.netrc
wandb: Appending key for api.wandb.ai to your netrc file: /homes/pcarboni/.netrc
wandb: Appending key for api.wandb.ai to your netrc file: /homes/pcarboni/.netrc
wandb: Tracking run with wandb version 0.19.1
wandb: Run data is saved locally in /work/tesi_pcarboni/cl_detr/models/ops/wandb/run-20250131_095824-ytguhelf
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run run_2025-01-31_09-58-24
wandb: ‚≠êÔ∏è View project at https://wandb.ai/pol_carboni-unimore/CL-DETR
wandb: üöÄ View run at https://wandb.ai/pol_carboni-unimore/CL-DETR/runs/ytguhelf
wandb: Tracking run with wandb version 0.19.1
wandb: Run data is saved locally in /work/tesi_pcarboni/cl_detr/models/ops/wandb/run-20250131_095824-fl54xo5o
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run run_2025-01-31_09-58-24
wandb: ‚≠êÔ∏è View project at https://wandb.ai/pol_carboni-unimore/CL-DETR
wandb: üöÄ View run at https://wandb.ai/pol_carboni-unimore/CL-DETR/runs/fl54xo5o
wandb: Tracking run with wandb version 0.19.1
wandb: Run data is saved locally in /work/tesi_pcarboni/cl_detr/models/ops/wandb/run-20250131_095824-kvejjeq4
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run run_2025-01-31_09-58-24
wandb: ‚≠êÔ∏è View project at https://wandb.ai/pol_carboni-unimore/CL-DETR
wandb: üöÄ View run at https://wandb.ai/pol_carboni-unimore/CL-DETR/runs/kvejjeq4
wandb: Tracking run with wandb version 0.19.1
wandb: Run data is saved locally in /work/tesi_pcarboni/cl_detr/models/ops/wandb/run-20250131_095824-9sqfnani
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run run_2025-01-31_09-58-24
wandb: ‚≠êÔ∏è View project at https://wandb.ai/pol_carboni-unimore/CL-DETR
wandb: üöÄ View run at https://wandb.ai/pol_carboni-unimore/CL-DETR/runs/9sqfnani
[rank2]:[W131 09:58:25.844730963 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 2]  using GPU 2 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank1]:[W131 09:58:25.918799837 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 1]  using GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank3]:[W131 09:58:25.975078070 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 3]  using GPU 3 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank0]:[W131 09:58:25.121108261 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 0]  using GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/work/tesi_pcarboni/CL-DETR/main.py:321: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(ckpt_path, map_location='cpu')
/work/tesi_pcarboni/CL-DETR/main.py:321: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(ckpt_path, map_location='cpu')
/work/tesi_pcarboni/CL-DETR/main.py:321: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(ckpt_path, map_location='cpu')
/work/tesi_pcarboni/CL-DETR/main.py:321: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(ckpt_path, map_location='cpu')
[rank0]: Traceback (most recent call last):
[rank0]:   File "/work/tesi_pcarboni/CL-DETR/main.py", line 428, in <module>
[rank0]:     main(args)
[rank0]:   File "/work/tesi_pcarboni/CL-DETR/main.py", line 321, in main
[rank0]:     checkpoint = torch.load(ckpt_path, map_location='cpu')
[rank0]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/torch/serialization.py", line 1384, in load
[rank0]:     return _legacy_load(
[rank0]:            ^^^^^^^^^^^^^
[rank0]:   File "/homes/pcarboni/.conda/envs/tesi/lib/python3.12/site-packages/torch/serialization.py", line 1647, in _legacy_load
[rank0]:     typed_storage._untyped_storage._set_from_file(
[rank0]: RuntimeError: storage has wrong byte size: expected %ld got %ld172529064726479769044096
Traceback (most recent call last):
  File "/work/tesi_pcarboni/cl_detr/models/ops/tools/launch.py", line 91, in <module>
    main()
  File "/work/tesi_pcarboni/cl_detr/models/ops/tools/launch.py", line 86, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/work/tesi_pcarboni/CL-DETR/main.py']' returned non-zero exit status 1.
srun: error: rezzonico: task 0: Exited with exit code 1
